### ISSUE TITLE
Unsupported operand type(s)

### ISSUE THREAD

**Issue by kmuriki** [PrincetonUniversity/globus-stats#1]
Excellent documentation! Kudos for that.

I tried to pull raw usage data from our endpoint but the script failed like this:

$ python get_globus_data.py -c ./globus_config.json -o ./data/  
Pull new Globus data!
[d47068d3-6d04-11e5-ba46-22000b92c6ec] None
Number of tasks 22005

Saving Result: endpoint_map_list_of_tasks.p

Saving Result: admin_endpoint_map.p

Traceback (most recent call last):
  File "get_globus_data.py", line 478, in <module>
    main()
  File "get_globus_data.py", line 464, in main
    measurement_map_map, users_set, endpoint_id_to_name_map = read_data_and_create_maps(endpoint_map_list_of_tasks, gconfig)
  File "get_globus_data.py", line 362, in read_data_and_create_maps
    measurement_map_map[endpoint]["num_files"].append(task["files_skipped"] + task["files_transferred"])
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

**Comment by hyojoonkim** [comment]
Hello, 

Sorry for the late reply; I just saw this now (I might have to fix my email notification to work correctly). I'll look into this asap. 

-Joon

**Comment by hyojoonkim** [comment]
Hello @kmuriki , 

So obviously, either `task["files_transferred"]` or `task["files_skipped"]` is "`None`", which is strange to me. Since the code only looks at succeeded transfer tasks that actually transferred more than 0 bytes, I am not sure why a task will have `"None"` for `files_transferred` (should be >0) or `file_skipped`(should be 0 or more). 

Any how, that's what Globus SDK returning is to you. So we will have to debug why this task is like this.

Can you replace below ([get_globus_data.py at line 361:](https://github.com/PrincetonUniversity/globus-stats/blob/f2eae904344fa0a1e7576d808000a1bbf26848a7/get_globus_data.py#L361))
> 
    # Get number of file
    measurement_map_map[endpoint]["num_files"].append(task["files_skipped"] + task["files_transferred"])
> 

TO:

>
    # Get number of file
    if task["files_transferred"]==None:
        print ("files_transferred value is 'None' for this task. Setting to 0. User was: %s, request time was: %s")%(task["owner_id"],task["request_time"])
        task["files_transferred"] = 0
    if task["files_skipped"]==None:
        print ("files_skipped value is 'None' for this task. Setting to 0. User was: %s, request time was: %s")%(task["owner_id"],task["request_time"])
        task["files_skipped"] = 0
    measurement_map_map[endpoint]["num_files"].append(task["files_skipped"] + task["files_transferred"])
> 

Then, let me know how it goes. If there are lots of output strings like `"files_transferred [or files_skipped] value is 'None'..."`, then that's not a good sign... We will have  to dig into it deeper. Above code is just replacing `None` to `0`, which might not be the right way to deal with it, especially if there are too many tasks like this. 

If you can, please pick a particular task with a "`None`" value and check it out in Globus.org based on the `owner_id (user)` and `request time`. Maybe you can see why that task returned "`None`" for `files_transferred` or `files_skipped`. 

Let me know!
